[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "airhammer"
version = "1.0"
dependencies = [
    "twisted",
    "wpa_supplicant",
]

[project.scripts]
airhammer = "airhammer:main"